export const FlatActionTypes = {

    ADD_FLAT: "ADD_FLAT",
    UPDATE_FLAT: "UPDATE_FLAT",
    DELETE_FLAT: "DELETE_FLAT",
    GET_FLAT: "GET_FLAT",
    GET_ALL_FLATS: "GET_ALL_FLATS",
    GET_FLATS_BY_COST: "GET_FLATS_BY_COST"
}