export const FlatBookingActionTypes = {
   
    ADD_FLATBOOKING : "ADD_FLATBOOKING ",
    UPDATE_FLATBOOKING  : "UPDATE_FLATBOOKING ",
    DELETE_FLATBOOKING  : "DELETE_FLATBOOKING",
    GET_FLATBOOKING  : "GET_FLATBOOKING ",
    GET_ALL_FLATBOOKINGS : "GET_ALL_FLATBOOKINGS"
    
    
}