export const LandlordActionTypes = {
   
    ADD_LANDLORD : "ADD_LANDLORD",
    UPDATE_LANDLORD : "UPDATE_LANDLORD",
    DELETE_LANDLORD : "DELETE_LANDLORD",
    GET_LANDLORD : "GET_LANDLORD",
    GET_ALL_LANDLORDS : "GET_ALL_LANDLORDS"
    
}